module.exports = {
   "id":"r",
   "name":"root",
   "children":[
      {
         "id":"personality",
         "name":"Big 5 ",
         "children":[
            {
               "id":"Neuroticism_parent",
               "name":"Emotional range",
               "category":"personality",
               "percentage":1,
               "children":[
                  {
                     "id":"Openness",
                     "name":"Openness",
                     "category":"personality",
                     "percentage":0.20399078437973817,
                     "sampling_error":0.34904999999999997,
                     "children":[
                        {
                           "id":"Adventurousness",
                           "name":"Adventurousness",
                           "category":"personality",
                           "percentage":0.026535592821239965,
                           "sampling_error":0.2897474
                        },
                        {
                           "id":"Artistic interests",
                           "name":"Artistic interests",
                           "category":"personality",
                           "percentage":0.012830785228883002,
                           "sampling_error":0.56284128
                        },
                        {
                           "id":"Emotionality",
                           "name":"Emotionality",
                           "category":"personality",
                           "percentage":0.9291014170594251,
                           "sampling_error":0.32568836
                        },
                        {
                           "id":"Imagination",
                           "name":"Imagination",
                           "category":"personality",
                           "percentage":0.2542390229086915,
                           "sampling_error":0.39370608
                        },
                        {
                           "id":"Intellect",
                           "name":"Intellect",
                           "category":"personality",
                           "percentage":0.2689129524400916,
                           "sampling_error":0.34802748
                        },
                        {
                           "id":"Liberalism",
                           "name":"Authority-challenging",
                           "category":"personality",
                           "percentage":0.6619011942255594,
                           "sampling_error":0.44719712
                        }
                     ]
                  },
                  {
                     "id":"Conscientiousness",
                     "name":"Conscientiousness",
                     "category":"personality",
                     "percentage":0.028512906392495513,
                     "sampling_error":0.43201472,
                     "children":[
                        {
                           "id":"Achievement striving",
                           "name":"Achievement striving",
                           "category":"personality",
                           "percentage":0.1930097483222458,
                           "sampling_error":0.39890796
                        },
                        {
                           "id":"Cautiousness",
                           "name":"Cautiousness",
                           "category":"personality",
                           "percentage":0.07426599191690786,
                           "sampling_error":0.43788952000000003
                        },
                        {
                           "id":"Dutifulness",
                           "name":"Dutifulness",
                           "category":"personality",
                           "percentage":0.010192659007711949,
                           "sampling_error":0.53559212
                        },
                        {
                           "id":"Orderliness",
                           "name":"Orderliness",
                           "category":"personality",
                           "percentage":0.9336307258676677,
                           "sampling_error":0.36934300000000003
                        },
                        {
                           "id":"Self-discipline",
                           "name":"Self-discipline",
                           "category":"personality",
                           "percentage":0.009852298573872612,
                           "sampling_error":0.46419272
                        },
                        {
                           "id":"Self-efficacy",
                           "name":"Self-efficacy",
                           "category":"personality",
                           "percentage":0.020150390769408902,
                           "sampling_error":0.49596456
                        }
                     ]
                  },
                  {
                     "id":"Extraversion",
                     "name":"Extraversion",
                     "category":"personality",
                     "percentage":0.1337070233470026,
                     "sampling_error":0.47340252,
                     "children":[
                        {
                           "id":"Activity level",
                           "name":"Activity level",
                           "category":"personality",
                           "percentage":0.08694332329996558,
                           "sampling_error":0.5832707199999999
                        },
                        {
                           "id":"Assertiveness",
                           "name":"Assertiveness",
                           "category":"personality",
                           "percentage":0.625377336647571,
                           "sampling_error":0.5310504
                        },
                        {
                           "id":"Cheerfulness",
                           "name":"Cheerfulness",
                           "category":"personality",
                           "percentage":0.477562778250563,
                           "sampling_error":0.41581808
                        },
                        {
                           "id":"Excitement-seeking",
                           "name":"Excitement-seeking",
                           "category":"personality",
                           "percentage":0.9188226193032524,
                           "sampling_error":0.44373124
                        },
                        {
                           "id":"Friendliness",
                           "name":"Outgoing",
                           "category":"personality",
                           "percentage":0.01965072540864453,
                           "sampling_error":0.51863944
                        },
                        {
                           "id":"Gregariousness",
                           "name":"Gregariousness",
                           "category":"personality",
                           "percentage":0.30601048541857606,
                           "sampling_error":0.5219262800000001
                        }
                     ]
                  },
                  {
                     "id":"Agreeableness",
                     "name":"Agreeableness",
                     "category":"personality",
                     "percentage":0.13196942718831867,
                     "sampling_error":0.46254404,
                     "children":[
                        {
                           "id":"Altruism",
                           "name":"Altruism",
                           "category":"personality",
                           "percentage":0.009876466648043336,
                           "sampling_error":0.5590054
                        },
                        {
                           "id":"Cooperation",
                           "name":"Cooperation",
                           "category":"personality",
                           "percentage":0.035576430622983574,
                           "sampling_error":0.50853624
                        },
                        {
                           "id":"Modesty",
                           "name":"Modesty",
                           "category":"personality",
                           "percentage":0.0216734149298788,
                           "sampling_error":0.53792372
                        },
                        {
                           "id":"Morality",
                           "name":"Uncompromising",
                           "category":"personality",
                           "percentage":0.02140490277873854,
                           "sampling_error":0.5065219599999999
                        },
                        {
                           "id":"Sympathy",
                           "name":"Sympathy",
                           "category":"personality",
                           "percentage":0.7831718870330533,
                           "sampling_error":0.56820224
                        },
                        {
                           "id":"Trust",
                           "name":"Trust",
                           "category":"personality",
                           "percentage":0.009450488270533578,
                           "sampling_error":0.5310668
                        }
                     ]
                  },
                  {
                     "id":"Neuroticism",
                     "name":"Emotional range",
                     "category":"personality",
                     "percentage":1,
                     "sampling_error":0.35852048000000003,
                     "children":[
                        {
                           "id":"Anger",
                           "name":"Fiery",
                           "category":"personality",
                           "percentage":1,
                           "sampling_error":0.3262526
                        },
                        {
                           "id":"Anxiety",
                           "name":"Prone to worry",
                           "category":"personality",
                           "percentage":1,
                           "sampling_error":0.36852767999999997
                        },
                        {
                           "id":"Depression",
                           "name":"Melancholy",
                           "category":"personality",
                           "percentage":1,
                           "sampling_error":0.4594136
                        },
                        {
                           "id":"Immoderation",
                           "name":"Immoderation",
                           "category":"personality",
                           "percentage":0.9843872574067438,
                           "sampling_error":0.335582
                        },
                        {
                           "id":"Self-consciousness",
                           "name":"Self-consciousness",
                           "category":"personality",
                           "percentage":1,
                           "sampling_error":0.49810259999999995
                        },
                        {
                           "id":"Vulnerability",
                           "name":"Susceptible to stress",
                           "category":"personality",
                           "percentage":0.989283978813757,
                           "sampling_error":0.37255648
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "id":"needs",
         "name":"Needs",
         "children":[
            {
               "id":"Challenge_parent",
               "name":"Challenge",
               "category":"needs",
               "percentage":1,
               "children":[
                  {
                     "id":"Challenge",
                     "name":"Challenge",
                     "category":"needs",
                     "percentage":1,
                     "sampling_error":0.84705212
                  },
                  {
                     "id":"Closeness",
                     "name":"Closeness",
                     "category":"needs",
                     "percentage":1,
                     "sampling_error":0.89207692
                  },
                  {
                     "id":"Curiosity",
                     "name":"Curiosity",
                     "category":"needs",
                     "percentage":0.00889921678942499,
                     "sampling_error":0.79948692
                  },
                  {
                     "id":"Excitement",
                     "name":"Excitement",
                     "category":"needs",
                     "percentage":0.12275693129260454,
                     "sampling_error":0.8011018000000001
                  },
                  {
                     "id":"Harmony",
                     "name":"Harmony",
                     "category":"needs",
                     "percentage":1,
                     "sampling_error":0.83302164
                  },
                  {
                     "id":"Ideal",
                     "name":"Ideal",
                     "category":"needs",
                     "percentage":0.008735507055362258,
                     "sampling_error":0.79326828
                  },
                  {
                     "id":"Liberty",
                     "name":"Liberty",
                     "category":"needs",
                     "percentage":0.9541769925351598,
                     "sampling_error":0.86323284
                  },
                  {
                     "id":"Love",
                     "name":"Love",
                     "category":"needs",
                     "percentage":0.007942822680313395,
                     "sampling_error":0.86644196
                  },
                  {
                     "id":"Practicality",
                     "name":"Practicality",
                     "category":"needs",
                     "percentage":0.33582868302609986,
                     "sampling_error":0.86722176
                  },
                  {
                     "id":"Self-expression",
                     "name":"Self-expression",
                     "category":"needs",
                     "percentage":0.9302393525410492,
                     "sampling_error":0.81700056
                  },
                  {
                     "id":"Stability",
                     "name":"Stability",
                     "category":"needs",
                     "percentage":0.7368375407955612,
                     "sampling_error":0.82054876
                  },
                  {
                     "id":"Structure",
                     "name":"Structure",
                     "category":"needs",
                     "percentage":0.009946936957933162,
                     "sampling_error":0.08291392
                  }
               ]
            }
         ]
      },
      {
         "id":"values",
         "name":"Values",
         "children":[
            {
               "id":"Self-enhancement_parent",
               "name":"Self-enhancement",
               "category":"values",
               "percentage":0.03917973125323333,
               "children":[
                  {
                     "id":"Conservation",
                     "name":"Conservation",
                     "category":"values",
                     "percentage":0.19685282864331696,
                     "sampling_error":0.5794326
                  },
                  {
                     "id":"Openness to change",
                     "name":"Openness to change",
                     "category":"values",
                     "percentage":0.93381276949964,
                     "sampling_error":0.6144698
                  },
                  {
                     "id":"Hedonism",
                     "name":"Hedonism",
                     "category":"values",
                     "percentage":0.4802828730711365,
                     "sampling_error":0.60919148
                  },
                  {
                     "id":"Self-enhancement",
                     "name":"Self-enhancement",
                     "category":"values",
                     "percentage":0.03917973125323333,
                     "sampling_error":0.5798372399999999
                  },
                  {
                     "id":"Self-transcendence",
                     "name":"Self-transcendence",
                     "category":"values",
                     "percentage":0.7764798075860696,
                     "sampling_error":0.5529051199999999
                  }
               ]
            }
         ]
      }
   ]
}
